blog/config/routes.rb
Rails.application.routes.draw do

   root 'article#index'

  resources :article

end

blog/app/models/article.rb
class Article < ActiveRecord::Base




end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/article_controller.rb
class ArticleController < ApplicationController

  before_action :validate_params, only: [:create]

  def create
    create_params = created_params
    @article = Article.new(create_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to (article_path(@article)), notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      end
    end

  end

  def show
    @article = Article.where(id: params[:id])
  end

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all.order("created_at DESC")
  end

  private

  def created_params
    permitted_params = params.require(:article).permit(:title, :content, :author)
  end

  def validate_params
    if params[:article][:title].blank? || params[:article][:content].blank? || params[:article][:author].blank?
      render json: { message: "params invalid", status: :unprocessable_entity }
    end
  end

end

blog/app/helpers/article_helper.rb
module ArticleHelper
end

blog/app/views/article/_form.html.haml
.well.whiteBack
  = form_for @article, url: article_index_path, html: {class: 'form-horizontal'} do |f|
    - if @article.errors.any?
      #error_explanation
        %h4= "Please fix the following errors. - #{pluralize(@article.errors.count, "error")}"
        %ul
          - @article.errors.full_messages.each do |msg|
            %li= msg
    .row
      .col-md-6
        .form-group
          = f.label :title, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :content, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :content, class: 'form-control'
        .form-group
          = f.label :author, class: 'control-label col-md-2'
          .col-md-10
            = f.text_field :author, class: 'form-control'

    .row
      .col-md-12
        .text-center
          = submit_tag "Save", class:'btn btn-primary'
          = link_to 'Cancel', article_index_path, class:'btn btn-danger'

blog/app/views/article/index.html.haml
.row
  .col-sm-12
    %h2 Articles
.well.whiteBack
  .row
    .col-sm-6
      = link_to 'New Article', new_article_path, {class:'btn btn-primary'}
  %table.table.table-bordered.table-striped.margin10-both.table-hover.showRow
    %thead
      %th Title
      %th Content
      %th Author
    %tbody.pointerCursor
      - @articles.each do |notification|
        %tr{'data-link'=>article_path(notification)}
          %td= notification.title
          %td= notification.content
          %td= notification.author

blog/app/views/article/new.html.haml
%h2 Articles

= render 'form'

blog/app/views/article/show.html.haml
.row
  .col-sm-12
    %h2 Articles
.well.whiteBack
  .row
    %table.table.table-bordered.table-striped.margin10-both.table-hover.showRow
      %thead
        %th Title
        %th Content
        %th Author
      %tbody.pointerCursor
        %td= @article.first.title
        %td= @article.first.content
        %td= @article.first.author
  .row
    .col-md-12.text-center
      = link_to 'All notifications', article_index_path , class:'btn btn-danger'

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>